### ISSUE TITLE
ImportError: cannot import name 'parse_uri'

### ISSUE THREAD

**Issue by Payam-Ebadi** [nanoporetech/pipeline-structural-variation#18]
Hello everyone, Can somebody help me with this error on PSV:

> File "/home/grid/miniconda3/envs/pipeline-structural-variation-v2/lib/python3.6/site-packages/snakemake/__init__.py", line 593, in snakemake
    snakefile, overwrite_first_rule=True, print_compilation=print_compilation
  File "/home/grid/miniconda3/envs/pipeline-structural-variation-v2/lib/python3.6/site-packages/snakemake/workflow.py", line 1083, in include
    if is_local_file(snakefile):
  File "/home/grid/miniconda3/envs/pipeline-structural-variation-v2/lib/python3.6/site-packages/snakemake/common.py", line 65, in is_local_file
    from smart_open import parse_uri
ImportError: cannot import name 'parse_uri'

I appreciate if someone give me an answer for this.

**Comment by hannahgoldswain** [comment]
I am also stuck here and would appreciate some help!

**Comment by hannahgoldswain** [comment]
Hi, I think you have to install smart_open, I installed it with conda install.

Hope it works, it got past that error for me!

**Comment by cjw85** [comment]
Hi @hannahgoldswain,

Thank you for reporting this. It doesn't look like an error with the pipeline-sv code per se, rather with the snakemake package and its use of the `smart_open` pacakge. I will make `smart_open` a direct dependency of the pipeline conde.

**Comment by valerii-pokrytiuk** [comment]
@Payam-Ebadi you have to install older version of `smart_open` -- the latest one doesn't allow to import `parse_uri`. 

In my case `conda install smart_open=3` worked

**Comment by namronb** [comment]
> @Payam-Ebadi you have to install older version of `smart_open` -- the latest one doesn't allow to import `parse_uri`.
> 
> In my case `conda install smart_open=3` worked

Thanks, the "=3" was what I was missing to make it work!
