### ISSUE TITLE
Why the 'REF' column of 'my_sample_sniffles.vcf' is consists of "N" 

### ISSUE THREAD

**Issue by weir12** [nanoporetech/pipeline-structural-variation#9]
Hi:
Thank you for developing this pipeline.I don't know much about variant calling currently.
My fastq files (ACGU)are generated by **Direct RNA Sequencing**(DRS) of Nanopore.I noticed that this pipeline is prepared for DNA sample.I don't know if this is going to make a big difference in SV calling.
In spite of this, I finished the entire pipeline with the default parameters.
However,I found that column **REF** in `sniffles.vcf` is entirely composed of **N**
I am sure that reference sequence(ACGT) has a base in that position.
I know my question might be a little silly...
Many thanks!
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  my_sample/alignment/my_sa
mple_minimap2.bam
NC_045512.2     10      0       N       <DUP>   .       PASS    PRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=NC_045512.2;END=10;STD_quant_start=1.01929;STD_quant_stop=0;Kurtosis_quant_start=3.43254;Kurtosis_quant_stop=66.8768;SVTYPE=DUP;SUPTYPE=SR;SVLEN=20413;STRANDS=-+;STRANDS2=154,0,154,0;RE=154
;REF_strand=88930,1;AF=0.00172869    GT:DR:DV        0/0:88931:154
NC_045512.2     10      1       N       <DUP>   .       PASS    PRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=NC_045512.2;END=10;STD_quant_start=1.04497;STD_quant_stop=0;Kurtosis_quant_start=4.16431;Kurtosis_quant_stop=45.1848;SVTYPE=DUP;SUPTYPE=SR;SVLEN=10314;STRANDS=-+;STRANDS2=175,0,175,0;RE=175;REF_strand=83423,1;AF=0.00209333    GT:DR:DV        0/0:83424:175
NC_045512.2     10      2       N       <DUP>   .       PASS    PRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=NC_045512.2;END=10;STD_quant_start=1.046;STD_quant_stop=0.433861;Kurtosis_quant_start=1.53721;Kurtosis_quant_stop=7.05895;SVTYPE=DUP;SUPTYPE=SR;SVLEN=2320;STRANDS=-+;STRANDS2=170,0,170,0;RE=170;REF_strand=151094,2;AF=0.00112385       GT:DR:DV        0/0:151096:170
```

**Comment by fritzsedlazeck** [comment]
Hi,
yes makes a big difference if you use RNA vs. DNA data. The assumption here is a continuous stretch mapped to the genome, while in the case of RNA this will likely be mapped into an exon structure. (Maybe more for Humans than COVID in your case). 

For the N in the reference column: This is just a default way to display the information according to the VCF standard. The three events you are looking for here are marked as Duplication events starting at the first positions of the COVID strain (if I am not mistaken). 

Hope that helps
Fritz

**Comment by weir12** [comment]
@fritzsedlazeck 
I can no other answer make, but, thanks, and thanks :)
